name: Lint PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

permissions: read-all

jobs:
  lint:
    permissions:
      contents: read
    if: ${{ github.head_ref != 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - name: Checkout PR branch
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install dependencies
      run: npm install @commitlint/cli @commitlint/config-conventional

    - name: Validate PR title
      run: |
        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        echo "$PR_TITLE" | npx commitlint --config commitlint.config.js
